#!/bin/bash

set -euo pipefail
set -x

readonly origin="${origin:-core}"

wait_for_scheduler_ready() {
  local state
  local counter="0"

  while [[ $counter -lt 15 ]]; do
    state=$(kubectl get cs scheduler -o jsonpath="{.conditions[].type}")
    if [[ "${state}" == "Healthy" ]]; then
      return 0
    else
      counter=$((counter + 1))
      sleep 2
    fi
  done

  echo "Timed out waiting for scheduler to be ready."
  return 1
}


kubectl cordon node-0
vagrant ssh node-0 -- sudo hab svc unload "${origin}"/kubernetes-scheduler
vagrant ssh node-0 -- sudo hab pkg install "${origin}"/kubernetes-scheduler
vagrant ssh node-0 -- sudo hab svc load "${origin}"/kubernetes-scheduler

wait_for_scheduler_ready

kubectl uncordon node-0
