#!/bin/bash

set -euo pipefail

readonly dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

find "${dir}/../config/" -iname '*.kubeconfig' -print0 | xargs -0 rm -vf

for i in {0..5}; do
  node_kubeconfig="${dir}/../config/node-${i}/kubeconfig"
  mkdir -p "$(dirname "${node_kubeconfig}")"
  kubectl config set-cluster kubernetes-the-hab-way \
    --certificate-authority="${dir}/../certificates/ca.pem" \
    --embed-certs=true \
    --server=https://192.168.222.10:6443 \
    --kubeconfig="${node_kubeconfig}"

  kubectl config set-credentials system:node:node-${i} \
    --client-certificate="${dir}/../certificates/node-${i}/node.pem" \
    --client-key="${dir}/../certificates/node-${i}/node-key.pem" \
    --embed-certs=true \
    --kubeconfig="${node_kubeconfig}"

  kubectl config set-context default \
    --cluster=kubernetes-the-hab-way \
    --user=system:node:node-${i} \
    --kubeconfig="${node_kubeconfig}"

  kubectl config use-context default --kubeconfig="${node_kubeconfig}"
done

kubectl config set-cluster kubernetes-the-hab-way \
  --certificate-authority="${dir}/../certificates/ca.pem" \
  --embed-certs=true \
  --server=https://192.168.222.10:6443 \
  --kubeconfig="${dir}/../config/kube-proxy.kubeconfig"

kubectl config set-credentials kube-proxy \
  --client-certificate="${dir}/../certificates/kube-proxy.pem" \
  --client-key="${dir}/../certificates/kube-proxy-key.pem" \
  --embed-certs=true \
  --kubeconfig="${dir}/../config/kube-proxy.kubeconfig"

kubectl config set-context default \
  --cluster=kubernetes-the-hab-way \
  --user=kube-proxy \
  --kubeconfig="${dir}/../config/kube-proxy.kubeconfig"

kubectl config use-context default --kubeconfig="${dir}/../config/kube-proxy.kubeconfig"
