#!/bin/bash

set -euo pipefail

readonly dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd "${dir}/../certificates" >/dev/null
trap 'popd >/dev/null' EXIT

rm -vf ./*.csr ./*.pem

# ca
cfssl gencert -initca ca-csr.json | cfssljson -bare ca

# etcd
cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -hostname=192.168.222.10,192.168.222.11,192.168.222.12,192.168.222.13,192.168.222.14,192.168.222.15,127.0.0.1 \
  -profile=kubernetes \
  etcd-csr.json | cfssljson -bare etcd
