#!/bin/bash

set -euo pipefail

readonly tmpdir=$(mktemp -d /tmp/hab-install-XXXX)
mkdir -p "${tmpdir}"

pushd "${tmpdir}" >/dev/null
trap 'popd >/dev/null; rm -rf "${tmpdir}"' EXIT

readonly hab_bintray_url="https://dl.bintray.com/habitat/stable/linux/x86_64/hab-0.61.0-20180815171844-x86_64-linux.tar.gz"

curl -sSL "${hab_bintray_url}" -o hab.tar.gz
tar -xvf hab.tar.gz --strip-components 1
install -m 0755 hab /usr/local/bin/

if ! getent group hab >/dev/null; then
  groupadd hab
fi
if ! getent passwd hab >/dev/null; then
  useradd -g hab hab
fi
