#!/bin/bash

set -euo pipefail

readonly tmpdir=$(mktemp -d /tmp/hab-install-XXXX)
mkdir -p "${tmpdir}"

pushd "${tmpdir}" >/dev/null
trap 'popd >/dev/null; rm -rf "${tmpdir}"' EXIT

readonly hab_bintray_url="https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux"

curl -sSL "${hab_bintray_url}" -o hab.tar.gz
tar -xvf hab.tar.gz --strip-components 1
install -m 0755 hab /usr/local/bin/

if ! getent group hab >/dev/null; then
  groupadd hab
fi
if ! getent passwd hab >/dev/null; then
  useradd -g hab hab
fi
