#!/bin/bash

set -euo pipefail

readonly dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

kubectl config set-cluster kubernetes-the-hab-way \
  --certificate-authority="${dir}/../certificates/ca.pem" \
  --embed-certs=true \
  --server=https://192.168.222.10:6443

kubectl config set-credentials kubernetes-the-hab-way-admin \
  --client-certificate="${dir}/../certificates/admin.pem" \
  --client-key="${dir}/../certificates/admin-key.pem"

kubectl config set-context kubernetes-the-hab-way \
  --cluster=kubernetes-the-hab-way \
  --user=kubernetes-the-hab-way-admin

kubectl config use-context kubernetes-the-hab-way
